### PR TITLE
Update version to 2024.1

### LINKED ISSUE #10: @conda-forge-admin, please add user @ZzEeKkAa
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by ZzEeKkAa**
Checklist

* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: #9 
Closes: #10
Closes: #11

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
@conda-forge-admin, please rerender

**Comment by ZzEeKkAa** [comment]
From the error log:
```
/Users/runner/miniforge3/conda-bld/spirv-tools_1716652032354/work/tools/objdump/objdump.cpp:64:20: error: 'path' is unavailable: introduced in macOS 10.15 - see https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk
```

It looks like package requires macOS 15 +, but I'm not sure how to add exception to the generated recipes...

**Comment by hmaarrfk** [comment]
See these 4 lines. 

https://github.com/conda-forge/opencv-feedstock/blob/5fba48ab99792965c420f5387909a96105e82d11/recipe/conda_build_config.yaml#L4

You should be able to search our documentation for them to better understand.

**Comment by ZzEeKkAa** [comment]
Thank you @hmaarrfk ! I guess I found better solution in the doc: https://conda-forge.org/docs/maintainer/knowledge_base/#newer-c-features-with-old-sdk

So the CI is green now and ready to merge.

**Comment by hmaarrfk** [comment]
Add yourself as a maintainer ;) and rerender?

**Comment by ZzEeKkAa** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Thank you

**Comment by ZzEeKkAa** [comment]
@hmaarrfk why did not it uploaded to the conda-forge channel? https://anaconda.org/conda-forge/spirv-tools/files

**Comment by hmaarrfk** [comment]
i'm not sure. i retriggered a build by just pushing to main.

while frowned upon, it is "ok" in these scenerios...

https://github.com/conda-forge/spirv-tools-feedstock/runs/25528205184

**Comment by hmaarrfk** [comment]
seems like the builds are now uploading.

**Comment by ZzEeKkAa** [comment]
Thank you!

**Pull request merged**
